service :
  db:
    image: postgres:16-alpine
    container_name: 69-s1-db
    ports:
     - 54327:5432
  environment:
     - POSTGRES_PASSWORD=2310
     - POSTGRES_USER=porramee
     - POSTGRES_DB=porramee
volumes:
./data:/var/lib/postgresql/data
